<a href="https://colab.research.google.com/github/teleyun/bigdata/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_%EC%97%B0%EC%8A%B5(%EC%98%88%EB%AC%B8%EC%82%AC)_Chapter02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sklearn
sklearn.__version__

'1.0.2'

붓꽃 예측(p.172)

In [14]:
from sklearn.datasets import load_iris
iris = load_iris()

iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [59]:
import pandas as pd
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_df['lable'] = iris.target
iris_df.head()

X = iris_df.loc[:,'sepal length (cm)':'petal width (cm)']
y = iris_df[['lable']]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 11)

print(len(X_train), len(X_test), len(y_train), len(y_test))

from sklearn.tree import DecisionTreeClassifier
df_clt = DecisionTreeClassifier(random_state  =11)
df_clt.fit(X_train, y_train)

pred = df_clt.predict(X_test)

dir(sklearn.metrics)
from sklearn.metrics import accuracy_score
ac_score = accuracy_score(y_test, pred)
ac_score


120 30 120 30


0.9333333333333333

데이터 전처리(p180)

LabelEncoder 
- 숫자의 크기가 모형에 반영
- 선형회귀와 같은 알고리즘에는 부적합
- 트리 계열에 적합

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터','TV', '냉장고', '전자레인지', '컴퓨터' ]

encoder = LabelEncoder()

encoder.fit(items)

labels = encoder.transform(items)

print(labels)

# dir(encoder)
print(encoder.classes_)

items

[0 1 2 3 0 1 2 3]
['TV' '냉장고' '전자레인지' '컴퓨터']


['TV', '냉장고', '전자레인지', '컴퓨터', 'TV', '냉장고', '전자레인지', '컴퓨터']

원-핫 인코딩(sklearn)

In [6]:
from sklearn.preprocessing import OneHotEncoder
# from sklearn import *
# dir(sklearn.linear_model)
import numpy as np
import pandas as pd

labels = labels.reshape(-1,1)
labels

oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

columns_ = encoder.classes_
type(oh_labels)
oh = oh_labels.toarray()
pd.DataFrame(oh, columns = columns_ ).astype('int')

TV  냉장고  전자레인지  컴퓨터
0   1    0      0    0
1   0    1      0    0
2   0    0      1    0
3   0    0      0    1
4   1    0      0    0
5   0    1      0    0
6   0    0      1    0
7   0    0      0    1

원-핫 인코딩(getdummies)

In [18]:
import pandas as pd

# dir(pd)
item_df = pd.DataFrame({'item' : items})
dummy = pd.get_dummies(item_df)

dummy

item_TV  item_냉장고  item_전자레인지  item_컴퓨터
0        1         0           0         0
1        0         1           0         0
2        0         0           1         0
3        0         0           0         1
4        1         0           0         0
5        0         1           0         0
6        0         0           1         0
7        0         0           0         1

스케일링(정규화)

In [41]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data

iris_df = pd.DataFrame(iris_data, columns = iris.feature_names)

iris_df.head()

iris_df.head()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(iris_df)
iris_std_scaled = scaler.transform(iris_df)
pd.DataFrame(iris_std_scaled, columns = iris.feature_names).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

스케일링(최대-최소 정규화)

In [49]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_df_minmax_scaled = scaler.transform(iris_df)

pd.DataFrame(iris_df_minmax_scaled, columns = iris.feature_names).agg(['min', 'max'])

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
min                0.0               0.0                0.0               0.0
max                1.0               1.0                1.0               1.0

In [68]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print(np.round(train_array.reshape(-1), 2))
print(np.round(train_scaled.reshape(-1),2))


# scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print(np.round(test_array.reshape(-1), 2))
print(np.round(test_scaled.reshape(-1),2))


[ 0  1  2  3  4  5  6  7  8  9 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0 1 2 3 4 5]
[0.  0.2 0.4 0.6 0.8 1. ]
