In [4]:
import numpy as np
import pandas as pd

a1 = np.array([1,2,3])
a1.reshape(-1,1).shape

(3, 1)

In [5]:
a2 = np.arange(10)
a2.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
a3 = np.ones(10).astype('float')
a3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
a4 = np.zeros(10)
a4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
full_a = np.full((4, 3), 'a')
random_a = np.random.random(3)
random_a

array([0.12027228, 0.95099557, 0.62536873])

In [9]:
array1 = np.arange(12)
array2 = array1.reshape(2,3,2, order='F')

array3 = array2.reshape(1,-1)
type(array3)

array4 = array2.flatten()
type(array4)

numpy.ndarray

In [10]:
array5 = np.eye(5).astype('int')
ans = pd.DataFrame(array5).rename(columns={1:'a'}, inplace=False)
ans.agg('mean')

0    0.2
a    0.2
2    0.2
3    0.2
4    0.2
dtype: float64

In [28]:
x = np.array([13, 13, 13, 13, 13, 13, 14,4,5,6,77,78,454])
# np.percentile(x, 25)
np.percentile(x,50)
# pd.DataFrame(x).agg(['mean','var','max','min'] )

13.0