In [27]:
import numpy as np
import pandas as pd

a1 = np.array([1,2,3])
a1.reshape(-1,1).shape

(3, 1)

In [21]:
a2 = np.arange(10)
a2.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
a3 = np.ones(10).astype('float')
a3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
a4 = np.zeros(10)
a4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
full_a = np.full((4, 3), 'a')
random_a = np.random.random(3)
random_a

array([0.22209435, 0.09110625, 0.96116671])

In [62]:
array1 = np.arange(12)
array2 = array1.reshape(2,3,2, order='F')

array3 = array2.reshape(1,-1)
type(array3)

array4 = array2.flatten()
type(array4)

numpy.ndarray

In [88]:
array5 = np.eye(5).astype('int')
ans = pd.DataFrame(array5).rename(columns={1:'a'}, inplace=False)
ans

0  a  2  3  4
0  1  0  0  0  0
1  0  1  0  0  0
2  0  0  1  0  0
3  0  0  0  1  0
4  0  0  0  0  1